--GR8_TIPO_USUARIO
INSERT INTO GR8_TIPO_USUARIO VALUES (1,'Competidor');
INSERT INTO GR8_TIPO_USUARIO VALUES (2,'Socializador');

--GR8_USUARIO
INSERT INTO GR8_USUARIO VALUES (1,'Oliver','Lat','example@com',1,'pass');
INSERT INTO GR8_USUARIO VALUES (2,'Mari','ano','another@com',2,'pass');
INSERT INTO GR8_USUARIO VALUES (3,'Samu','ulo','other@com',2,'pass');

--GR8_NIVEL
INSERT INTO GR8_NIVEL VALUES (1,'Principiante');
INSERT INTO GR8_NIVEL VALUES (2,'Intermedio');
INSERT INTO GR8_NIVEL VALUES (3,'Avanzado');
INSERT INTO GR8_NIVEL VALUES (4,'Experto');

--GR8_CATEGORIA
INSERT INTO GR8_CATEGORIA VALUES (1,'Acción',1);
INSERT INTO GR8_CATEGORIA VALUES (2,'Acción',1);
INSERT INTO GR8_CATEGORIA VALUES (3,'Acción',1);
INSERT INTO GR8_CATEGORIA VALUES (4,'Acción',1);
INSERT INTO GR8_CATEGORIA VALUES (5,'Autos',2);
INSERT INTO GR8_CATEGORIA VALUES (6,'Autos',2);
INSERT INTO GR8_CATEGORIA VALUES (7,'Autos',2);
INSERT INTO GR8_CATEGORIA VALUES (8,'Autos',2);
INSERT INTO GR8_CATEGORIA VALUES (9 ,'Aventuras',3);
INSERT INTO GR8_CATEGORIA VALUES (10,'Aventuras',3);
INSERT INTO GR8_CATEGORIA VALUES (11,'Aventuras',3);
INSERT INTO GR8_CATEGORIA VALUES (12,'Aventuras',3);
INSERT INTO GR8_CATEGORIA VALUES (13,'Didácticos',4);
INSERT INTO GR8_CATEGORIA VALUES (14,'Didácticos',4);
INSERT INTO GR8_CATEGORIA VALUES (15,'Didácticos',4);
INSERT INTO GR8_CATEGORIA VALUES (16,'Didácticos',4);

--GR8_JUEGO
INSERT INTO GR8_JUEGO VALUES (1,'God Of War','READ IT BOY!',4);
INSERT INTO GR8_JUEGO VALUES (2,'League Of Legends','that toxic game',1);
INSERT INTO GR8_JUEGO VALUES (3,'Breath of the wild','Nintendo',3);
INSERT INTO GR8_JUEGO VALUES (4,'Dreams','can´t recall',2);
INSERT INTO GR8_JUEGO VALUES (5,'Surgeon Simulator','Walt Disney',7);
INSERT INTO GR8_JUEGO VALUES (6,'Uncharted','Fox',8);
INSERT INTO GR8_JUEGO VALUES (7,'Cyber Punk 2077','Marvel',5);
INSERT INTO GR8_JUEGO VALUES (8,'Square Pants Sponge Bob','Nick',6);
INSERT INTO GR8_JUEGO VALUES (9,'Diamond Game','Hideo Kojima',15);

--GR8_JUEGA
INSERT INTO GR8_JUEGA VALUES (false,1,1);
INSERT INTO GR8_JUEGA VALUES (false,1,2);
INSERT INTO GR8_JUEGA VALUES (false,1,3);
INSERT INTO GR8_JUEGA VALUES (true,2,4);
INSERT INTO GR8_JUEGA VALUES (true,2,5);

--RECOMENDACION
INSERT INTO GR8_RECOMENDACION VALUES(1,'example@org.com',1,1);

--COMENTARIO
INSERT INTO GR8_COMENTARIO VALUES (1,1,1,'1999-01-08 04:05:06','wUENARDO');

--COMENTA
INSERT INTO GR8_COMENTA VALUES (1,1,'1999-01-08 04:05:06',NULL);


-- GR8_NIVEL
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (1,'nec, malesuada ut, sem.');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (2,'parturient montes, nascetur ridiculus');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (3,'eros turpis non enim.');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (4,'dapibus id, blandit at,');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (5,'Duis sit amet diam eu');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (6,'Donec');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (7,'vitae mauris sit');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (8,'eget, venenatis a,');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (9,'Sed id');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (10,'magna a neque. Nullam');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (11,'nec urna et');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (12,'ut');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (13,'senectus');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (14,'aliquet, sem');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (15,'tellus. Aenean');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (16,'ornare, lectus ante dictum mi,');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (17,'pharetra');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (18,'libero lacus,');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (19,'fringilla purus mauris a nunc.');
INSERT INTO GR8_NIVEL (id_nivel_juego,descripcion) VALUES (20,'consectetuer');

-- GR8_CATEGORIA
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (1,'magna. Suspendisse',10);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (2,'justo. Proin non massa',19);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (3,'pede.',17);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (4,'metus. In nec orci. Donec',13);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (5,'ultricies dignissim lacus. Aliquam',1);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (6,'ipsum. Donec',8);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (7,'lacus.',11);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (8,'mi felis, adipiscing',15);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (9,'sed sem egestas blandit. Nam',4);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (10,'sed',6);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (11,'ut',18);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (12,'ipsum',3);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (13,'mi',6);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (14,'vestibulum, neque sed dictum eleifend,',2);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (15,'ornare. Fusce mollis. Duis sit',13);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (16,'eget, volutpat',18);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (17,'molestie tortor nibh sit',9);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (18,'nisi a',15);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (19,'Integer sem elit, pharetra ut,',13);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (20,'volutpat ornare, facilisis',17);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (21,'nascetur ridiculus mus. Proin',8);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (22,'Sed',9);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (23,'Curabitur dictum. Phasellus',6);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (24,'sem elit, pharetra ut,',3);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (25,'cursus purus. Nullam scelerisque',15);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (26,'tincidunt',18);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (27,'luctus',14);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (28,'mi enim, condimentum eget, volutpat',13);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (29,'Duis risus odio, auctor vitae,',17);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (30,'Cras pellentesque. Sed',15);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (31,'ornare,',12);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (32,'eu',18);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (33,'vitae, aliquet nec, imperdiet nec,',18);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (34,'Nunc quis arcu vel',4);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (35,'facilisis non, bibendum sed, est.',18);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (36,'vulputate eu, odio. Phasellus',5);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (37,'ipsum.',18);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (38,'odio.',11);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (39,'orci luctus et ultrices',7);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (40,'fringilla mi lacinia',9);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (41,'egestas',14);
INSERT INTO GR8_CATEGORIA (id_categoria,descripcion,id_nivel_juego) VALUES (42,'dictum',8);

-- GR8_JUEGO
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (1,'auctor','amet,',1);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (2,'consectetuer','libero nec ligula consectetuer rhoncus.',41);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (3,'Donec','orci. Phasellus dapibus quam',30);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (4,'arcu. Nunc','lorem ac risus. Morbi metus.',42);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (5,'vitae','conubia nostra, per inceptos hymenaeos. Mauris ut quam',35);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (6,'massa.','lorem.',32);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (7,'in','euismod mauris eu elit. Nulla facilisi. Sed neque.',10);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (8,'Quisque tincidunt','egestas rhoncus. Proin nisl',16);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (9,'posuere','Duis cursus, diam at pretium aliquet, metus urna convallis',5);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (10,'Vestibulum ante','dolor. Nulla semper tellus id nunc',20);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (11,'magna.','libero. Morbi accumsan laoreet ipsum. Curabitur',19);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (12,'lectus quis','montes, nascetur ridiculus mus. Donec dignissim',3);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (13,'nec urna','Donec nibh enim, gravida sit amet, dapibus id, blandit',32);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (14,'dis parturient','a sollicitudin orci sem eget massa. Suspendisse eleifend.',11);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (15,'neque','pede. Cum',2);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (16,'Praesent eu','a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris',22);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (17,'gravida','in, dolor. Fusce feugiat. Lorem ipsum',16);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (18,'lorem vitae','elementum, lorem ut aliquam iaculis, lacus pede',37);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (19,'elit, pharetra','ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet,',10);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (20,'senectus et','pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero',15);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (21,'est, vitae','mauris. Integer',10);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (22,'nisl','velit',5);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (23,'ac','tempor bibendum. Donec felis orci,',31);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (24,'risus. In','non, bibendum sed, est.',21);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (25,'diam. Sed','lectus. Cum',11);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (26,'commodo hendrerit.','dapibus gravida. Aliquam tincidunt,',19);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (27,'est. Nunc','quis, pede.',29);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (28,'quis massa.','iaculis enim, sit amet ornare lectus justo',37);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (29,'dictum','dictum augue malesuada malesuada. Integer id magna',29);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (30,'vestibulum','sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed',23);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (31,'dui. Cras','Suspendisse ac metus',4);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (32,'dolor.','mollis. Phasellus libero mauris, aliquam eu, accumsan sed,',2);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (33,'ut','at arcu. Vestibulum ante ipsum primis in faucibus orci',36);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (34,'sem,','pede nec ante blandit viverra. Donec',5);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (35,'non','consectetuer euismod est',39);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (36,'blandit. Nam','Cras',39);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (37,'cursus,','condimentum. Donec at arcu. Vestibulum',12);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (38,'aliquet diam.','interdum. Curabitur dictum. Phasellus in felis. Nulla tempor',2);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (39,'auctor vitae,','erat eget',31);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (40,'cubilia Curae;','nec ligula consectetuer rhoncus.',16);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (41,'ante,','In tincidunt congue turpis. In condimentum. Donec at arcu.',30);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (42,'facilisis vitae,','sem egestas blandit.',8);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (43,'ante.','sed libero. Proin sed',19);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (44,'sociosqu','lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,',10);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (45,'tincidunt','ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu',22);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (46,'mus. Donec','penatibus et magnis',34);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (47,'vitae','Sed neque. Sed',40);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (48,'elit,','Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna.',30);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (49,'vulputate, nisi','gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.',15);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (50,'litora','neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est.',19);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (51,'sit','eleifend.',30);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (52,'lectus','urna. Nunc quis arcu vel quam dignissim',22);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (53,'diam lorem,','Etiam gravida molestie arcu. Sed eu',8);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (54,'pharetra, felis','arcu. Sed et libero.',4);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (55,'ultrices. Duis','ipsum cursus vestibulum. Mauris',29);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (56,'Fusce','odio',17);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (57,'Duis a','Ut sagittis lobortis mauris. Suspendisse',37);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (58,'purus mauris','euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit',19);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (59,'erat','vulputate velit',19);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (60,'Sed molestie.','Aliquam',24);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (61,'vulputate ullamcorper','inceptos hymenaeos. Mauris ut quam',11);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (62,'vitae diam.','et',22);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (63,'Cum','ridiculus mus. Proin vel arcu eu odio tristique',9);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (64,'euismod','dapibus ligula. Aliquam',4);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (65,'morbi tristique','Fusce feugiat. Lorem ipsum dolor sit amet,',27);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (66,'nascetur ridiculus','Pellentesque ut ipsum ac mi',37);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (67,'Etiam ligula','magna nec',40);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (68,'et','sagittis augue, eu tempor erat neque non quam. Pellentesque',15);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (69,'sed, sapien.','ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis',36);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (70,'eget,','neque sed dictum',29);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (71,'tempor erat','laoreet, libero et',25);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (72,'tristique','ut aliquam iaculis, lacus pede sagittis augue, eu tempor',18);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (73,'dignissim','eu elit.',24);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (74,'ante,','nascetur ridiculus mus.',8);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (75,'erat neque','Integer in magna. Phasellus dolor elit, pellentesque',28);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (76,'quis','sagittis semper.',21);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (77,'luctus','Nunc',7);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (78,'fermentum','enim. Nunc ut erat. Sed nunc est, mollis non,',9);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (79,'ut, pellentesque','libero. Integer in magna. Phasellus dolor elit,',1);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (80,'iaculis odio.','sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo',18);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (81,'metus. In','augue ut',23);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (82,'eu','Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui,',32);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (83,'ultrices','in consequat',26);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (84,'tincidunt','Lorem ipsum',19);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (85,'Mauris','erat vel pede',2);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (86,'elementum,','risus. Morbi metus.',11);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (87,'turpis nec','varius. Nam porttitor scelerisque neque. Nullam',24);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (88,'congue, elit','eu augue porttitor interdum.',27);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (89,'leo, in','ante. Maecenas',33);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (90,'penatibus','velit',1);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (91,'Integer','suscipit, est ac facilisis facilisis, magna tellus faucibus',23);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (92,'Donec consectetuer','ornare, libero at auctor ullamcorper, nisl arcu iaculis enim,',18);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (93,'Mauris','a, dui. Cras pellentesque.',7);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (94,'enim nec','diam. Sed diam lorem, auctor quis, tristique',15);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (95,'luctus. Curabitur','mollis non, cursus non, egestas a, dui.',37);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (96,'dignissim pharetra.','Maecenas malesuada fringilla est.',25);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (97,'nascetur ridiculus','accumsan',18);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (98,'magna a','congue, elit sed',6);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (99,'erat,','In at pede. Cras vulputate velit eu sem. Pellentesque',30);
INSERT INTO GR8_JUEGO (id_juego,nombre_juego,descripcion_juego,id_categoria) VALUES (100,'blandit.','semper rutrum. Fusce dolor quam, elementum',25);

--TIPO GR8_USUARIO
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (1,'molestie');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (2,'elementum');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (3,'posuere, enim nisl');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (4,'vitae risus. Duis');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (5,'ridiculus');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (6,'egestas.');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (7,'risus. Nunc ac sem ut dolor');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (8,'vitae odio');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (9,'adipiscing ligula. Aenean');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (10,'pretium neque. Morbi quis');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (11,'Mauris magna. ');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (12,'Mauris eu turpis. ');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (13,'fames ac turpis egestas. Fusce');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (14,'Sed');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (15,'lorem eu metus. In lorem.');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (16,'eget massa. Suspendisse');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (17,'arcu. Sed eu nibh vulputate');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (18,'purus ac tellus. Suspendisse');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (19,'Vestibulum accumsan neque');
INSERT INTO GR8_TIPO_USUARIO (id_tipo_usuario,descripcion) VALUES (20,'per inceptos hymenaeos. Mauris');

--GR8_USUARIO
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (1,'Karen','Mckenzie','consectetuer@arcuvelquam.com',8,'LBV82AJZ0IW');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (2,'Ria','Padilla','ridiculus.mus.Proin@Morbi.org',16,'XCQ17UYS4ES');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (3,'Astra','Fox','montes.nascetur@enimNuncut.com',18,'TUK05UGX6BH');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (4,'Evangeline','William','imperdiet@erat.co.uk',16,'IGG40CWG4TG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (5,'Jemima','Harrison','porttitor@nostra.com',18,'JQI65UCM7LE');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (6,'Helen','Newton','et.pede@aliquetne.com',20,'TRO84HNG3QH');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (7,'Emmanuel','Hoffman','euismod@cubiliaCurae.ca',17,'MHQ03LGH5MF');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (8,'Emma','Shaw','adipiscing@Aliquamerat.org',10,'GCO35WEM4SB');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (9,'Guy','Gates','consectetueret@Curabi.co.uk',7,'NVX16FZV3GZ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (10,'Brandon','Wolf','lobortis@felisullamcor.net',7,'BYC48NJQ1XC');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (11,'Dorian','Sutton','sed@ornarelectus.com',1,'RHG91VPC5VL');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (12,'Eden','Nieves','et.eros@ultricies.edu',1,'XON62CWF5NZ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (13,'Hanna','Clements','libero@tinciduntadipiscing.org',20,'UPU24OBQ7MG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (14,'Blake','Cain','convallis@acorci.net',7,'DJM10EGW2RS');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (15,'Addison','Floyd','elementum@convallis.edu',6,'ZHX38JKL9HF');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (16,'Nina','Norris','urna@conubianostraper.co.uk',2,'UQM95ZIQ2OE');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (17,'Brittany','Velazquez','malesuada@duntvehicula.edu',4,'MWM81JXV6AZ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (18,'Doris','Conley','laoreet@Maecena.co.uk',8,'UWJ05IXH9RQ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (19,'Ignacia','Berg','at@vehicula.edu',3,'UMO18QLO1BW');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (20,'Hu','Gilmore','Duis@augue.edu',3,'ADS11CTI8AW');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (21,'Hedwig','Whitley','convallis@nascetur.co.uk',12,'ZKH43MIL6MN');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (22,'Ariana','Vance','Vivamus@sociosquadlitora.ca',14,'ENS50MRN8PI');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (23,'Tanner','Maxwell','velit@nec.net',8,'SIP93PXZ5WS');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (24,'Harrison','Haley','sociis@lectusNullam.ca',14,'GKN51GOM0DV');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (25,'Jaime','Mckinney','velfaucibus@nulla.com',2,'PWA39HGJ1BQ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (26,'Brent','Glenn','non@enimnon.org',12,'WXJ93BUF6SJ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (27,'Orlando','West','aptent@Donecnibhenim.co.uk',11,'QCP16UVM3PM');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (28,'Nayda','Crawford','eu@Suspendissea.co.uk',6,'AND35WON9HZ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (29,'Brock','Kirk','pretium@semper.co.uk',7,'GAE48TAS9NT');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (30,'Quinn','Church','nec@justofaucibus.com',19,'GBJ51GUV8ZB');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (31,'Scarlett','Wooten','neque@ipsum.org',5,'XPD62KVA4RJ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (32,'Molly','Reeves','lacus@ipsumSuspendisse.ca',4,'LFT95ZFM9HP');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (33,'Ulric','Branch','taciti@dui.co.uk',11,'THK54UNZ3CP');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (34,'Caldwell','Spears','Proinmi@liberonec.co.uk',19,'MEN50FTL4OB');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (35,'Kadeem','Thornton','velit@eliteratvitae.co.uk',16,'DHL67ZKA9AZ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (36,'Iris','Myers','hendrerit@sedorcil.co.uk',2,'NCR05HFL3WN');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (37,'Karleigh','Gilbert','justo@purusmaurisa.org',14,'BVA18MGR7YU');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (38,'Jane','Walsh','eu@tincidunt.org',14,'YGX69DMI4JL');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (39,'Elton','Fitzgerald','Etiam@lobortis.co.uk',16,'MJA26TXH3PT');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (40,'Carolyn','Newman','Curabitur.egestas@arcu.org',9,'NLN08CYW6CV');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (41,'Nichole','Shepherd','commodo@idante.co.uk',18,'LUQ10WRB2XC');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (42,'Merrill','Cleveland','Aliquam@luctusaliquet.edu',6,'PNP71TKQ2NM');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (43,'Kasimir','Obrien','nunc@sit.ca',8,'LCY52KWD4UU');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (44,'Aladdin','Moody','auctor.vitae@vitaeerat.org',13,'BCI94USH7ZU');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (45,'Shelley','Lester','Duis.a@liberoconsectetuer.ca',19,'VRQ85LFJ6LV');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (46,'Justine','Barker','lorem@gravida.ca',15,'COJ08PUZ9NR');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (47,'Colin','Weiss','Aliquam@ametlorem.com',7,'WIA40EDP8RY');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (48,'Imelda','Frost','neque@antelectus.net',10,'JRP32HGZ9FE');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (49,'Guy','Kerr','mollis@acmattissemper.net',18,'DJV58GYP5DC');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (50,'Talon','Farrell','in.cursus@Fusce.co.uk',10,'MGW16JVE6AV');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (51,'Shana','Holland','turpis@consequa.net',4,'TZN73PPS3TD');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (52,'Henry','Schroeder','Pellen@gestas.net',15,'HPK96WNM0FL');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (53,'Yasir','Navarro','magna@convallisligula.co.uk',5,'AXY72NGW4SA');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (54,'Kitra','West','fringillami@utodio.co.uk',18,'WFA91JCM8BN');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (55,'Pamela','Haley','libero@purussapien.net',20,'HTB27FQO7GZ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (56,'Brenna','Mason','neque@liquamadipiscing.edu',15,'MRE92NBQ9DG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (57,'Armand','Douglas','dictum@Cras.com',8,'IGW74SKD2FY');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (58,'Rhona','Robinson','mauris@Phasellus.org',8,'JHE24ZEY0SG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (59,'Chase','Myers','natoque@Fusce.net',18,'WKQ02NRM9BB');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (60,'Kevyn','Sanchez','nunc@purus.org',19,'BOB09FLL3VS');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (61,'Clio','Blanchard','gravida@turpis.net',11,'FMI89WUX8MW');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (62,'Marah','Moses','id@Nuncullamcorper.com',15,'JBJ49ARI8AY');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (63,'Eaton','Garza','egestas@egetvarius.com',14,'TKS65NGQ0SG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (64,'Lamar','Hobbs','ultrices@acmetus.net',9,'EPN86QUN9IQ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (65,'Jennifer','Yates','malesuada@Aeneansedpede.ca',12,'HYY21EMT5ZL');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (66,'Sawyer','Puckett','turpis@sed.edu',9,'YCG79XYV8FO');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (67,'Abbot','Richardson','nisl.Nulla@sit.com',6,'LVO57BVH7BB');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (68,'Stewart','Malone','natoque@mi.net',19,'GWQ39LQS5EA');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (69,'Kirestin','Gilbert','velit@facilisis.edu',19,'HHM49XRJ7AF');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (70,'Quinn','Hancock','velit@ipsumdolorsit.ca',2,'RMC16CTW0RW');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (71,'Ralph','Herman','natoque@umpurusaccumsan.net',20,'BLX68GWK0ZG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (72,'Allegra','Mann','ante@velfaucibusid.co.uk',11,'WGT55JFW2IB');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (73,'Derek','Warner','mauriselit@Pumconvallis.ca',1,'ZMU27CTR8KQ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (74,'Cara','Dickson','eros@euduiCum.org',13,'JPG43QBN3UG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (75,'Cairo','Pittman','Praesent@namalesuada.net',15,'VAZ10LRR5ED');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (76,'Kennedy','Mcclure','Nullaeget@Vesti.edu',18,'EKB75LXM0SJ');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (77,'Wesley','Maynard','risus@NullamnislMaecenas.co.uk',18,'KFS52VVG1FA');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (78,'Judah','Parks','sollicitudin@Sed.com',17,'EOQ14QCD1PR');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (79,'Ulla','Savage','porta@acmi.ca',6,'VST61WWN7DF');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (80,'Omar','Faulkner','sagittis@eudui.edu',5,'QPK00VML7WV');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (81,'Dakota','Fernandez','lobortis@mi.co.uk',2,'GDR26NZO0KV');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (82,'Camilla','Richards','Mauris@orciadipiscing.net',6,'FSG19RCZ9WX');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (83,'Michael','Romero','Vivamus@in.net',2,'YMS14FKV2LX');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (84,'Bernard','Carney','arcu.vel@sedturpisnec.edu',19,'FPG89STL4PI');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (85,'Wang','Joyce','idmollisnec@euismodest.ca',17,'IQG74ISR1VA');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (86,'Byron','Hardin','augue@tempusmauriserat.net',5,'RPI83FLZ4LP');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (87,'Iliana','Baldwin','risus@ornareIn.com',20,'HRC60XRJ5ZA');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (88,'Harrison','Nielsen','vestibulum@porbibendum.com',12,'CAM21JFE6PU');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (89,'Malachi','Blake','Nulla.semper@at.edu',4,'DIP57HAL2HE');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (90,'Jesse','Head','a@musAenean.co.uk',8,'KAY54TVH6LW');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (91,'Illana','Gross','erat@vitaeodio.org',9,'OIO05EWZ4AL');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (92,'Karleigh','Alford','rutrum@vitae.ca',17,'NCQ82IST4GG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (93,'Kiona','Hensley','nec@mollisdui.org',10,'TNA23JXP6LA');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (94,'Ferris','Harding','in.dolor@necmollis.ca',9,'EXT00UOU7NW');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (95,'Hedy','Leblanc','nunc@Classaptent.ca',18,'ERV42WSJ9UI');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (96,'Amery','Pate','ut@facilisiSed.org',1,'WUL83NZZ7OG');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (97,'Noel','Young','nisi@Donec.net',9,'FTC81VCL0ZB');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (98,'Isaiah','Cunningham','ac.metus@lestieorci.ca',19,'TJV90TQB7OF');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (99,'Chastity','Jefferson','natoque@incursuset.com',13,'TJA57WEW6HW');
INSERT INTO GR8_USUARIO (id_usuario,nombre,apellido,email,id_tipo_usuario,password) VALUES (100,'Cairo','Curry','elit@elitafeugiat.co.uk',18,'PHJ15WBJ9PW');

--GR8_JUEGA
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (27,26, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (38,24, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (62,62, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (66,75, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (56,27, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (24,91, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (66,68, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (35,13, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (34,40, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (61,50, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (62,24, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (78,58, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,46, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (35,42, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (98,7, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (56,20, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (31,71, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (90,58, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (29,31, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (40,23, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (69,57, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (80,51, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (23,31, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (19,71, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (56,9, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (13,94, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (19,60, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (50,34, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (83,34, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (60,46, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (40,63, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,86, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (71,97, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (22,65, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (77,73, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (1,23, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (37,80, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (20,4, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (62,11, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,7, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (79,38, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (97,51, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (88,40, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (62,19, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (81,41, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (13,81, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (86,41, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (78,53, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (33,27, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (99,18, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (34,8, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (43,95, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (18,55, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (31,29, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (84,10, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (9,59, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (99,97, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (37,57, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (13,87, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (42,64, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (30,90, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (86,47, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (96,77, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (17,11, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (32,25, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (48,21, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (21,34, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (95,85, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (88,34, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (80,62, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (66,18, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (37,19, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (67,9, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (46,52, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (73,90, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (2,17, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (13,14, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (28,91, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (42,70, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (69,5, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (96,43, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (52,89, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (68,22, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (100,26, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (91,95, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (48,55, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (52,7, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (57,95, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (43,37, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (59,92, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (32,32, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (96,95, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (40,31, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (39,76, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (89,38, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (49,55, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (90,98, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (86,46, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (4,73, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (100,38, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (12,45, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (45,36, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (72,52, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (78,69, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (51,52, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (19,94, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (54,17, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (90,74, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (31,64, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (86,20, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (87,63, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (9,88, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (74,82, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (71,7, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (99,12, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (23,87, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (44,73, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (65,11, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (55,19, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (25,71, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (64,97, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (99,95, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (43,64, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (72,44, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (10,95, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (74,7, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (12,87, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (85,14, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (27,75, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (95,69, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (12,64, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (75,51, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (41,91, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (44,6, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (31,53, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (6,22, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (56,61, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (74,66, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (28,52, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (17,98, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (14,15, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (87,68, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (66,25, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (18,27, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (64,77, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (55,12, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (79,40, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (59,47, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (53,61, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (78,37, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (26,5, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (14,1, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (51,10, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (80,44, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (76,59, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (40,52, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (45,28, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (28,9, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (90,41, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (99,83, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (99,71, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,89, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (11,22, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (69,77, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (85,35, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (93,100, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (40,56, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (4,61, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (55,75, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (56,4, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (11,75, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (68,96, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (17,23, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (10,76, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (39,26, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (53,5, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (33,2, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (29,99, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (96,12, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (96,65, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (33,18, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (92,88, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (20,89, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (6,52, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (46,22, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (96,13, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (5,50, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (92,17, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (78,13, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (50,25, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (13,92, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (26,64, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (44,99, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (53,52, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (58,77, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (93,12, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (74,51, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (81,97, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (25,11, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (33,59, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (55,74, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (98,43, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (36,51, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (47,21, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (10,23, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (15,53, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (19,64, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (31,70, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (38,20, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (11,92, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (31,47, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,57, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (92,99, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (84,38, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (31,31, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (6,96, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (43,94, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,16, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,28, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (96,28, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (8,29, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (81,72, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (41,47, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (15,60, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (95,68, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (51,55, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (33,83, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (100,14, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (41,92, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (12,100, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (90,6, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,45, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (91,52, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (73,85, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (76,81, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (13,23, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (14,43, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (57,2, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (67,18, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (93,14, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (62,16, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (6,35, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (96,58, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (17,87, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (94,57, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (43,27, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (24,9, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (23,3, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (6,32, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (38,25, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (59,20, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (51,11, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (80,82, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (85,38, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (26,18, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (57,11, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (58,50, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (82,2, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (36,17, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (50,18, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (62,53, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (65,27, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (26,84, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (39,17, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (1,74, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (63,86, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (34,47, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (6,39, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (47,72, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (36,61, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (39,73, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (60,53, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (95,51, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (82,42, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (72,57, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (20,22, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (8,68, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (50,93, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (29,50, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (29,55, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (63,8, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (49,42, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (75,35, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (21,17, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (38,59, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (40,77, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (88,92, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (14,35, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (2,76, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (66,91, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (70,14, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (29,12, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (22,98, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (15,98, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (28,28, NULL);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (20,45, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (54,7, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (64,83, FALSE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (42,15, TRUE);
INSERT INTO GR8_JUEGA (id_usuario,id_juego, finalizado) VALUES (50,28, NULL);

--GR8_VOTO
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (1,10,27,26);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (2,2,38,24);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (3,6,62,62);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (4,2,66,75);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (5,2,56,27);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (6,7,24,91);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (7,6,66,68);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (8,10,35,13);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (9,8,34,40);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (10,10,61,50);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (11,7,62,24);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (12,5,78,58);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (13,6,70,46);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (14,1,35,42);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (15,2,98,7);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (16,8,56,20);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (17,3,31,71);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (18,6,90,58);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (19,3,29,31);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (20,8,40,23);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (21,5,69,57);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (22,9,80,51);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (23,10,23,31);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (24,8,19,71);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (25,7,56,9);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (26,3,13,94);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (27,10,19,60);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (28,9,50,34);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (29,5,83,34);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (30,8,60,46);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (31,2,40,63);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (32,2,70,86);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (33,6,71,97);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (34,1,22,65);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (35,3,77,73);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (36,6,1,23);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (37,6,37,80);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (38,5,20,4);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (39,6,62,11);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (40,9,70,7);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (41,10,79,38);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (42,4,97,51);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (43,8,88,40);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (44,8,62,19);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (45,3,81,41);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (46,10,13,81);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (47,1,86,41);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (48,2,78,53);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (49,5,33,27);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (50,6,99,18);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (51,2,34,8);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (52,2,43,95);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (53,1,18,55);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (54,3,31,29);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (55,7,84,10);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (56,1,9,59);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (57,5,99,97);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (58,8,37,57);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (59,10,13,87);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (60,10,42,64);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (61,2,30,90);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (62,6,86,47);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (63,2,96,77);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (64,10,17,11);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (65,6,32,25);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (66,4,48,21);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (67,1,21,34);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (68,2,95,85);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (69,2,88,34);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (70,7,80,62);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (71,5,66,18);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (72,7,37,19);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (73,9,67,9);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (74,8,46,52);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (75,2,73,90);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (76,10,2,17);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (77,10,13,14);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (78,4,28,91);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (79,10,42,70);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (80,10,69,5);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (81,6,96,43);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (82,6,52,89);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (83,3,68,22);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (84,1,100,26);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (85,9,91,95);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (86,7,48,55);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (87,6,52,7);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (88,3,57,95);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (89,9,43,37);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (90,2,59,92);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (91,10,32,32);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (92,7,96,95);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (93,4,40,31);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (94,2,39,76);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (95,1,89,38);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (96,7,48,55);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (97,4,90,98);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (98,5,86,46);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (99,7,4,73);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (100,7,100,38);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (101,10,12,45);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (102,10,45,36);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (103,2,72,52);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (104,6,78,69);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (105,2,51,52);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (106,10,19,94);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (107,6,54,17);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (108,4,90,74);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (109,1,31,64);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (110,2,86,20);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (111,2,87,63);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (112,7,9,88);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (113,5,74,82);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (114,7,71,7);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (115,9,99,12);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (116,8,23,87);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (117,2,44,73);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (118,10,65,11);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (119,10,55,19);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (120,4,25,71);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (121,10,64,97);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (122,10,99,95);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (123,6,42,64);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (124,6,72,44);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (125,3,10,95);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (126,1,74,7);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (127,9,12,87);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (128,7,85,14);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (129,6,27,75);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (130,3,95,69);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (131,9,12,64);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (132,2,75,51);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (133,10,41,91);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (134,7,44,6);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (135,4,31,53);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (136,2,6,22);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (137,1,56,61);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (138,7,74,66);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (139,4,28,52);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (140,5,17,98);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (141,7,14,15);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (142,7,87,68);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (143,10,66,25);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (144,10,18,27);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (145,2,64,77);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (146,6,55,12);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (147,2,79,40);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (148,10,59,47);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (149,6,53,61);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (150,4,78,37);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (151,1,26,5);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (152,2,14,1);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (153,2,51,10);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (154,7,80,44);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (155,5,76,59);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (156,7,40,52);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (157,9,45,28);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (158,8,28,9);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (159,2,90,41);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (160,10,99,83);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (161,10,99,71);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (162,4,70,89);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (163,10,11,22);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (164,10,69,77);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (165,6,85,35);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (166,6,93,100);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (167,3,40,56);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (168,1,4,61);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (169,9,55,75);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (170,7,56,4);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (171,6,11,75);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (172,3,68,96);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (173,9,17,23);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (174,2,10,76);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (175,10,39,26);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (176,7,53,5);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (177,4,33,2);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (178,2,29,99);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (179,1,96,12);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (180,7,96,65);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (181,4,33,18);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (182,5,92,88);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (183,7,20,89);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (184,7,6,52);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (185,10,46,22);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (186,10,96,13);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (187,2,5,50);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (188,6,92,17);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (189,2,78,13);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (190,10,50,25);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (191,6,13,92);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (192,4,26,64);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (193,1,44,99);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (194,2,53,52);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (195,2,58,77);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (196,7,93,12);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (197,5,74,51);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (198,7,81,97);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (199,9,25,11);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (200,8,33,59);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (201,2,55,74);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (202,10,98,43);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (203,10,36,51);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (204,4,47,21);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (205,10,10,23);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (206,10,15,53);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (207,6,19,64);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (208,6,31,70);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (209,3,38,20);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (210,1,11,92);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (211,9,31,47);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (212,7,69,57);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (213,6,92,99);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (214,3,84,38);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (215,9,31,31);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (216,2,6,96);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (217,10,43,94);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (218,7,70,16);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (219,4,70,28);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (220,2,96,28);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (221,1,8,29);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (222,7,81,72);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (223,4,41,47);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (224,5,15,60);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (225,7,95,68);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (226,7,51,55);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (227,10,33,83);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (228,10,100,14);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (229,2,41,92);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (230,6,12,100);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (231,2,90,6);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (232,10,70,45);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (233,6,91,52);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (234,4,73,85);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (235,1,76,81);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (236,2,13,23);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (237,2,14,43);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (238,7,57,2);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (239,5,66,18);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (240,7,93,14);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (241,9,62,16);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (242,8,6,35);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (243,2,96,58);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (244,10,17,87);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (245,10,94,57);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (246,4,43,27);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (247,10,24,9);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (248,10,23,3);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (249,6,6,32);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (250,6,38,25);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (251,3,59,20);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (252,1,51,11);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (253,9,80,82);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (254,7,84,38);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (255,6,26,18);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (256,3,57,11);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (257,9,58,50);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (258,2,82,2);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (259,10,36,17);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (260,7,50,18);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (261,4,62,53);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (262,2,65,27);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (263,1,26,84);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (264,7,39,17);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (265,4,1,74);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (266,5,63,86);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (267,7,34,47);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (268,7,6,39);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (269,10,47,72);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (270,10,36,61);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (271,2,39,73);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (272,6,60,53);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (273,2,95,51);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (274,10,82,42);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (275,6,72,57);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (276,4,20,22);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (277,1,8,68);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (278,2,50,93);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (279,2,29,50);
INSERT INTO GR8_VOTO (id_voto,valor_voto,id_usuario,id_juego) VALUES (280,7,29,55);
