--TIPO_USUARIO
INSERT INTO GR8_TIPO_USUARIO VALUES (1,'Competidor');
INSERT INTO GR8_TIPO_USUARIO VALUES (2,'Socializador');

--USUARIO
INSERT INTO GR8_USUARIO VALUES (1,'Oliver','Lat','example@com',1,'pass');
INSERT INTO GR8_USUARIO VALUES (2,'Mari','ano','another@com',2,'pass');
INSERT INTO GR8_USUARIO VALUES (3,'Samu','ulo','other@com',2,'pass');

--NIVEL
INSERT INTO GR8_NIVEL VALUES (1,'Principiante');
INSERT INTO GR8_NIVEL VALUES (2,'Intermedio');
INSERT INTO GR8_NIVEL VALUES (3,'Avanzado');
INSERT INTO GR8_NIVEL VALUES (4,'Experto');

--CATEGORIA
INSERT INTO GR8_CATEGORIA VALUES (1,'Acción',1);
INSERT INTO GR8_CATEGORIA VALUES (2,'Acción',1);
INSERT INTO GR8_CATEGORIA VALUES (3,'Acción',1);
INSERT INTO GR8_CATEGORIA VALUES (4,'Acción',1);
INSERT INTO GR8_CATEGORIA VALUES (5,'Autos',2);
INSERT INTO GR8_CATEGORIA VALUES (6,'Autos',2);
INSERT INTO GR8_CATEGORIA VALUES (7,'Autos',2);
INSERT INTO GR8_CATEGORIA VALUES (8,'Autos',2);
INSERT INTO GR8_CATEGORIA VALUES (9 ,'Aventuras',3);
INSERT INTO GR8_CATEGORIA VALUES (10,'Aventuras',3);
INSERT INTO GR8_CATEGORIA VALUES (11,'Aventuras',3);
INSERT INTO GR8_CATEGORIA VALUES (12,'Aventuras',3);
INSERT INTO GR8_CATEGORIA VALUES (13,'Didácticos',4);
INSERT INTO GR8_CATEGORIA VALUES (14,'Didácticos',4);
INSERT INTO GR8_CATEGORIA VALUES (15,'Didácticos',4);
INSERT INTO GR8_CATEGORIA VALUES (16,'Didácticos',4);

--JUEGO
INSERT INTO GR8_JUEGO VALUES (1,'God Of War','READ IT BOY!',4);
INSERT INTO GR8_JUEGO VALUES (2,'League Of Legends','that toxic game',1);
INSERT INTO GR8_JUEGO VALUES (3,'Breath of the wild','Nintendo',3);
INSERT INTO GR8_JUEGO VALUES (4,'Dreams','can´t recall',2);
INSERT INTO GR8_JUEGO VALUES (5,'Surgeon Simulator','Walt Disney',7);
INSERT INTO GR8_JUEGO VALUES (6,'Uncharted','Fox',8);
INSERT INTO GR8_JUEGO VALUES (7,'Cyber Punk 2077','Marvel',5);
INSERT INTO GR8_JUEGO VALUES (8,'Square Pants Sponge Bob','Nick',6);
INSERT INTO GR8_JUEGO VALUES (9,'Diamond Game','Hideo Kojima',15);

--JUEGA
INSERT INTO GR8_JUEGA VALUES (false,1,1);
INSERT INTO GR8_JUEGA VALUES (false,1,2);
INSERT INTO GR8_JUEGA VALUES (false,1,3);
INSERT INTO GR8_JUEGA VALUES (true,2,4);
INSERT INTO GR8_JUEGA VALUES (true,2,5);

--RECOMENDACION
-- INSERT INTO GR8_RECOMENDACION VALUES(1,'example@org.com',1,1);